apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce # Make sure to create the directory structure on your host: C:\temp\mysql-data
  hostPath:
    path: "/run/desktop/mnt/host/c/temp/mysql-data"  # Use a path that's accessible in Docker Desktop 
    type: DirectoryOrCreate