apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: crda-namespace
data:
  init.sql: |
    -- Create database first
    CREATE DATABASE IF NOT EXISTS base_crda;
    USE base_crda;

    SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
    START TRANSACTION;
    SET time_zone = "+00:00";

    -- Create app user and grant permissions
    CREATE USER IF NOT EXISTS 'crda_user'@'%' IDENTIFIED BY 'placeholder_password';
    GRANT SELECT, INSERT, UPDATE, DELETE ON base_crda.* TO 'crda_user'@'%';

    -- Table structure for table `services_utilisateur`
    CREATE TABLE `services_utilisateur` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `prenom` varchar(255) DEFAULT NULL,
      `nom` varchar(255) DEFAULT NULL,
      `cin` varchar(255) DEFAULT NULL,
      `numero_transaction` varchar(255) DEFAULT NULL,
      `certificat_propriete_terre` tinyint(1) DEFAULT NULL,
      `copie_piece_identite_fermier` tinyint(1) DEFAULT NULL,
      `copie_piece_identite_nationale` tinyint(1) DEFAULT NULL,
      `demande_but` tinyint(1) DEFAULT NULL,
      `copie_contrat_location_terrain` tinyint(1) DEFAULT NULL,
      `autres_documents` tinyint(1) DEFAULT NULL,
      `sujet` varchar(255) DEFAULT NULL,
      `status` varchar(255) NOT NULL DEFAULT 'قيد الانتظار',
      PRIMARY KEY (`id`),
      UNIQUE KEY `unique_service` (`cin`, `sujet`),
      KEY `idx_cin` (`cin`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    -- Table structure for table `rapport`
    CREATE TABLE `rapport` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `nom` varchar(255) NOT NULL,
      `prenom` varchar(255) NOT NULL,
      `cin` varchar(50) NOT NULL,
      `sujet` varchar(255) NOT NULL,
      `surface` decimal(10,2) NOT NULL,
      `limites_terrain` text NOT NULL,
      `localisation` varchar(255) NOT NULL,
      `superficie_batiments_anciens` decimal(10,2) NOT NULL,
      `observations` text DEFAULT NULL,
      PRIMARY KEY (`id`),
      UNIQUE KEY `idx_cin_sujet` (`cin`, `sujet`),
      KEY `idx_cin` (`cin`),
      CONSTRAINT `fk_rapport_service` FOREIGN KEY (`cin`, `sujet`)
        REFERENCES `services_utilisateur` (`cin`, `sujet`) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    -- Table structure for table `results`
    CREATE TABLE `results` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `sujet` varchar(255) NOT NULL,
      `nom` varchar(255) NOT NULL,
      `prenom` varchar(255) NOT NULL,
      `cin` varchar(255) NOT NULL,
      `numero_transaction` varchar(255) NOT NULL,
      `statut` enum('بصدد الدرس','مقبول','مرفوض') NOT NULL DEFAULT 'بصدد الدرس',
      PRIMARY KEY (`id`),
      UNIQUE KEY `unique_service` (`cin`,`sujet`),
      CONSTRAINT `fk_results_service` FOREIGN KEY (`cin`, `sujet`)
        REFERENCES `services_utilisateur` (`cin`, `sujet`) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    -- Table structure for table `utilisateur`
    CREATE TABLE `utilisateur` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `nom_user` varchar(100) NOT NULL,
      `prenom_user` varchar(100) NOT NULL,
      `sex_user` enum('homme','femme') NOT NULL,
      `cin_user` varchar(15) NOT NULL,
      `email_user` varchar(255) NOT NULL,
      `password_user` varchar(255) NOT NULL,
      `role_user` enum('directeur','gerant','chef_dentreprise','pending') NOT NULL,
      `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
      `status_user` enum('pending','approved','rejected') DEFAULT 'pending',
      PRIMARY KEY (`id`),
      UNIQUE KEY `email_unique` (`email_user`),
      UNIQUE KEY `cin_unique` (`cin_user`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

    -- Initial data with bcrypt hashed passwords (hash for '58877615')
    INSERT INTO `utilisateur` (`nom_user`, `prenom_user`, `sex_user`, `cin_user`, `email_user`, `password_user`, `role_user`, `status_user`) VALUES
    ('najwa', 'karrouchi', 'femme', '00001', 'najwakarrouchi@gmail.com', '$2b$10$rPg8jdTpMTNcWY3tNmOi7.rORWP3DfS7WOMQj8dQXLAYSKDhR9VfO', 'chef_dentreprise', 'approved'),
    ('najwa', 'karrouchi', 'femme', '00002', 'najwakarrouchi2222@gmail.com', '$2b$10$rPg8jdTpMTNcWY3tNmOi7.rORWP3DfS7WOMQj8dQXLAYSKDhR9VfO', 'gerant', 'approved'),
    ('najwa', 'karrouchi', 'femme', '00003', 'najwakarrouchi3333@gmail.com', '$2b$10$rPg8jdTpMTNcWY3tNmOi7.rORWP3DfS7WOMQj8dQXLAYSKDhR9VfO', 'directeur', 'approved');

    COMMIT;
