apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: crda-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      # Restore security context from working config
      securityContext:
        runAsUser: 999
        fsGroup: 999
      
      initContainers:
      - name: permission-fix
        image: busybox
        command: ["sh", "-c", "chown -R 999:999 /var/lib/mysql && chmod -R 750 /var/lib/mysql"]
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql

      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_DATABASE
          value: "base_crda"
        - name: MYSQL_USER
          value: "crda_user"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: app-password
        - name: MYSQL_ARGS  # Add back from working config
          value: "--default-authentication-plugin=mysql_native_password"
        
        ports:
        - containerPort: 3306
          name: mysql
        
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-init-script
          mountPath: /docker-entrypoint-initdb.d
        
        # Liveness probe using shell for variable substitution
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysqladmin ping -u$MYSQL_USER -p$MYSQL_PASSWORD"
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
        
        # Readiness probe using shell for variable substitution
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e 'SELECT 1'"
          initialDelaySeconds: 15
          periodSeconds: 10

      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-init-script
        configMap:
          name: mysql-init-script
