apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-exporter-config
  namespace: crda-namespace
data:
  .my.cnf: |
    [client]
    user=root
    password=${MYSQL_ROOT_PASSWORD}
    host=mysql-service
    port=3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: crda-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9104"
    spec:
      containers:
      - name: mysql-exporter
        image: prom/mysqld-exporter:v0.15.0
        ports:
        - containerPort: 9104
          name: mysql-exporter
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: DATA_SOURCE_NAME
          value: "root:$(MYSQL_ROOT_PASSWORD)@(mysql-service:3306)/"
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysqld_exporter
        args:
        - --config.my-cnf=/etc/mysqld_exporter/.my.cnf
        - --collect.info_schema.tables
        - --collect.info_schema.innodb_metrics
        - --collect.global_status
        - --collect.global_variables
        - --collect.slave_status
        - --collect.info_schema.processlist
        - --collect.perf_schema.tableiowaits
        - --collect.perf_schema.indexiowaits
        - --collect.perf_schema.tablelocks
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
      - name: mysql-config
        configMap:
          name: mysql-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter-service
  namespace: crda-namespace
spec:
  selector:
    app: mysql-exporter
  ports:
  - port: 9104
    targetPort: 9104
  type: ClusterIP